swagger: "2.0"
info:
  version: "0.0.1"
  title: Woolies X tech challenge API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /api/user:
    get:
      description: "Exercise 1 - user endpoint that respond with name and token"
      operationId: "GetUser"
      parameters: []
      responses:
        200:
          description: "user name and token"
          schema:
            $ref: "#/definitions/User"
      x-swagger-router-controller: "GetUser"
  /api/sort:
    get:
      description: "Exercise 2 - endpoint for sorting products"
      operationId: "SortProducts"
      parameters:
        - in: "query"
          name: "sortOption"
          description: "option for sorting"
          required: true
          type: "string"
          enum:
            - "Low"
            - "High"
            - "Ascending"
            - "Descending"
            - "Recommended"
      responses:
        200:
          description: "An array of sorted products"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Product"
      x-swagger-router-controller: "SortProducts"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  User:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Name of user"
      token:
        type: "string"
        description: "user access token"
  Product:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Name of the product"
      price:
        type: "number"
        description: "Price of the product"
      quantity:
        type: "integer"
        description: "Quantity of the product"
